### ISSUE TITLE
Runtime of the method?

### ISSUE THREAD

**Issue by utkarshmall13** [Hanzy1996/CE-GZSL#1]
How long does it usually take for a sample training run? I'm currently running this model on CUB using the given example parameters and it is taking a significant runtime (hours for 10s of iterations). Why is this significantly slower than the baselines compared against, like TF-VAEGAN? Is there a way to improve the runtime?

**Comment by Hanzy1996** [comment]
Thanks for your interest in our work.

In our experiments, the computation for the class-level contrastive embedding loss costs a lot of GPU memory. Thus, we calculate this loss with the form of 'for-loop', which corresponds to the function 'class_score_for_loop' and it slows down the training. To improve the runtime, you can use the function  'class_score_in_matrix' with a smaller batch size. As I have tested, using the matrix-form loss with the batch size of 512 takes about one hour (~140 epochs) to get similar results.

**Comment by utkarshmall13** [comment]
This sounds good! great work BTW.
