### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by vvtyy1999** [Hanzy1996/CE-GZSL#12]
I want to train with my own dataset, but I don't know how to make a dataset similar to that in this article. I'd like to know how to make res101.mat and att.splits.mat files in XLSA file?

**Comment by Hanzy1996** [comment]
Much appreciation for your interest. You can use the pre-trained ResNet101 to get the res101.mat. The att_split.mat is the annotation from the corresponding dataset.

**Comment by rongtongxueya** [comment]
same question.I wonder if there is any code for this. I use the bert model to convert the caption of other public data sets into semantic features, but the vector value of the semantic features varies from time to time

**Comment by Hanzy1996** [comment]
> same question.I wonder if there is any code for this. I use the bert model to convert the caption of other public data sets into semantic features, but the vector value of the semantic features varies from time to time

Perhaps you could check the way of using Bert. Or you can try CLIP text encoder. Hope this can help you.
