### ISSUE TITLE
About sent_splits.mat

### ISSUE THREAD

**Issue by NanAlbert** [Hanzy1996/CE-GZSL#14]
Hello, I would like to know how to generate the file sent_splits.mat or where to get the file of other datasets, e.g., AwA2, SUN, APY. 
Thank you so much!

**Comment by 1maojian1** [comment]
@NanAlbert hello,I have the same problem，Have you solved it now？

**Comment by NanAlbert** [comment]
> @NanAlbert hello,I have the same problem，Have you solved it now？

As I know so far, there is no CNN-RNN sentence embeddings for AwA2, SUN and APY datasets.

**Comment by 1maojian1** [comment]
你好，请问您在AWA1，AWA2数据集中可以跑到论文中的效果吗？我按照作者给的参数在AWA1中只能跑到h= 67.5，论文中h = 69.1






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hanzy1996/CE-GZSL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月24日(星期天) 晚上10:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hanzy1996/CE-GZSL] About sent_splits.mat (Issue #14)





 
Closed #14 as completed.

**Comment by rongtongxueya** [comment]
same question，How should such semantic data sets be generated，I want to build my own data set

**Comment by NanAlbert** [comment]
> same question，How should such semantic data sets be generated，I want to build my own data set

As I mentioned before, there are no CNN-RNN sentence embeddings available for the AwA2, SUN, and APY datasets. However, you could consider using language models like BERT to generate semantic data for your own dataset.
