### ISSUE TITLE
SUN数据集训练不稳定

### ISSUE THREAD

**Issue by yangjingqi99** [Hanzy1996/CE-GZSL#17]
作者您好，我在运行SUN 数据集时很容易出现NAN的情况，但在其他数据集上都不会有这个问题，请问是模型本身的问题（比如说WGAN训练不稳定），还是SUN数据集本身有脏数据呢？

**Comment by Hanzy1996** [comment]
十分感谢您的问题！训练SUN时确实比较容易出现不稳定的情况，这个问题我们也还正在研究，我们可能会在将来的工作中讨论这个问题。
