### ISSUE TITLE
SUN's H

### ISSUE THREAD

**Issue by Xiao-lv-lol** [Hanzy1996/CE-GZSL#19]
Hello, the H I got on SUN by using the parameters you provided and the method in the paper is 2% less than the result in your paper, I wonder if you have encountered such a situation. Could you please provide SUN's training parameters again?
`--dataset` SUN \
--class_embedding att \
--syn_num 100 \
--batch_size 1024 \
--attSize 102 \
--nz 102 \
--embedSize 2048 \
--outzSize 512 \
--nhF 1024 \
--ins_weight 0.01 \
--cls_weight 0.01 \
--ins_temp 0.1 \
--cls_temp 0.1 \
--manualSeed 4115 \
--nclass_all 717 \
--nclass_seen 645 \
--gpus 1 \
--lr_decay_epoch 100 \
--lr 0.00005‘

**Comment by via815via** [comment]
I have the same problem. My paramters is same as yours. Do you solve this problem?

**Comment by Hanzy1996** [comment]
SUN needs more epoch training, about 1,000 epochs. Please refer to the updated [hyper-parameters.](https://github.com/Hanzy1996/CE-GZSL/issues/2#issuecomment-874472906)

**Comment by 1maojian1** [comment]
I want to ask if you can reproduce it in awa2 dataset.The result I reproduced is 1.2% smaller than that of the paper.
python CE_GZSL.py 
--dataset AWA2 
--class_embedding att 
--syn_num 2400 
--batch_size 2048 
--attSize 85 
--nz 85 
--embedSize 2048 
--outzSize 512 
--nhF 2048 
--ins_weight 0.001
 --cls_weight 0.001 
--cls_temp 0.1 
--manualSeed 9182 
--lr_decay_epoch 10 
--nclass_all 50 
--nclass_seen 40 
--lr 1e-4
