### ISSUE TITLE
Could you provide the result on CUB dataset when using the att attribute?

### ISSUE THREAD

**Issue by Neko9810** [Hanzy1996/CE-GZSL#4]
I notice that you use sent attributes of CUB dataset, but we usually use att attributes  on CUB, like CLSWGAN/TF-VAEGAN and so on. Could you please provide your result when using att attributes for fair comparison?

**Comment by Hanzy1996** [comment]
Much appreciation for your interest!

We have tested our method on CUB using the attribute semantic descriptor, but the results are not as good (U=52.4, S=60.9, H=56.4) as using the sentence semantic descriptor. You can also replace the sent with the attribute in the codes.
Besides, we find that some other methods, like CADA-VAE[1], cycle-CLSWGAN[2], etc., also use the sentence semantic descriptor for CUB. And our results on CUB can still outperform theirs.

Best wishes!

[1] Generalized Zero- and Few-Shot Learning via Aligned Variational Autoencoders. Edgar Schonfeld, Sayna Ebrahimi, Samarth Sinha, Trevor Darrell, and Zeynep Akata. CVPR2019.
[2] Multi-modal Cycle-consistent Generalized Zero-Shot Learning. Rafael Felix, Vijay Kumar B G, Ian Reid, and Gustavo Carneiro. ECCV2018

**Comment by zhihou7** [comment]
Hi @Hanzy1996， could you provide sentence semantic or attribute semantic descriptor for all dataset? e.g. SUN, AWA

**Comment by Hanzy1996** [comment]
Hi @zhihou7, the semantic descriptors of other datasets have already been updated. Due to Github's limitations, I cannot upload all data as it is too large. If you need other information about the datasets, you can download them from the link in the README.md.

**Comment by zhihou7** [comment]
@Hanzy1996 Many thanks to you!

**Comment by xxxzhi** [comment]
Hi @Hanzy1996, I can run the code successfully with your provide attribute. e.g.

    python CE_GZSL.py --dataset AWA1 --class_embedding attri --syn_num 100 --batch_size 2048 --attSize 1024 --nz 1024 --embedSize 2048 --outzSize 512 --nhF 2048 --ins_weight 0.001 --cls_weight 0.001 --ins_temp 0.1 --cls_temp 0.1 --manualSeed 3483 --nclass_all 200 --nclass_seen 150

I suffer from an error about embedding size. Could you help me solve this? I'm not familiar with Domain Adaption.

Best Regards,

**Comment by zhihou7** [comment]
Hi @Hanzy1996, I can run the code successfully with your provide attribute. e.g.

    python CE_GZSL.py --dataset AWA1 --class_embedding attri --syn_num 100 --batch_size 2048 --attSize 1024 --nz 1024 --embedSize 2048 --outzSize 512 --nhF 2048 --ins_weight 0.001 --cls_weight 0.001 --ins_temp 0.1 --cls_temp 0.1 --manualSeed 3483 --nclass_all 200 --nclass_seen 150

I suffer from an error about embedding size. Could you help me solve this? I'm not familiar with Domain Adaption.

Best Regards,

**Comment by Hanzy1996** [comment]
HI, @zhihou7 , for AWA1/2, attSize=85, nclass_all=50, nclass_seen=40.

**Comment by sailing3658** [comment]
Hi, @Hanzy1996, could you please provide your result on the CUB dataset when using the att attributes for conventional ZSL or the parameters for CUB dataset when using the att attribute? Thanks a lot!
