### ISSUE TITLE
Keras implementation

### ISSUE THREAD

**Issue by webcsm** [Hanzy1996/CE-GZSL#5]
Hi @Hanzy1996 , I've implemented a Keras port of your code. What's the best way to share it with the community?

**Comment by Hanzy1996** [comment]
Hi, @webcsm , much appreciation for your implementation! I am so sorry that I am a little confused about what you said about `share it with the community'. I have never done this before, so I have no idea what you mean. Could you please provide more details?

**Comment by webcsm** [comment]
I guess I can share it in my github account, but for people interested in the paper to find it, my suggestion would be to add a link to it in you README or something like that, if you agree.

**Comment by Hanzy1996** [comment]
Much appreciation for your explaination! Sure, that's a good suggestion. After you share your Keras implementation in your github, please leave a comment and I can add a link in the README.

**Comment by webcsm** [comment]
This is the link: https://github.com/webcsm/ce-gzsl-keras

Thank you!

**Comment by Hanzy1996** [comment]
Much appreciation for your effort!

Best Regards!
