### ISSUE TITLE
GPU需求和训练时间

### ISSUE THREAD

**Issue by dongfengxijian** [Hanzy1996/CE-GZSL#6]
感谢你们分享的工作。你好，我想请问一下训练你们所提出的GZSL框架需要多大显存的GPU，对应的训练时间是多长？谢谢！

**Comment by Hanzy1996** [comment]
您好！谢谢您的关注！我们的实验所需的GPU显存最多需要10G（我们使用的是2080ti），由于不同数据集所需的batch size和语义描述特征的维度不一样，所以所需的显存和消耗的时间也不太一样，具体的数据还需要重新统计。

**Comment by dongfengxijian** [comment]
非常感谢您的回复！我想确认一下自己的设备能否做相关工作。现在经过您的指导，了解大致情况了。有机会就向您请教！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月16日(星期二) 下午2:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Hanzy1996/CE-GZSL] GPU需求和训练时间 (#6)





 
您好！谢谢您的关注！我们的实验所需的GPU显存最多需要10G（我们使用的是2080ti），由于不同数据集所需的batch size和语义描述特征的维度不一样，所以所需的显存和消耗的时间也不太一样，具体的数据还需要重新统计。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rongtongxueya** [comment]
我想咨询一个问题，为啥我使用同一个BERT对同一个公开数据集提取语义特征，生成的语义特征的向量值的大小不一样啊？
