### ISSUE TITLE
Flower dataset

### ISSUE THREAD

**Issue by webcsm** [Hanzy1996/CE-GZSL#7]
Hi @Hanzy1996 , the flower dataset that I found on the internet contains only data splits and images.

Could you share the link to the text embeddings? Or ideally, a link to the FLO dataset you used in your experiments?

**Comment by webcsm** [comment]
I found it here: https://github.com/akshitac8/tfvaegan

More specifically, on this link: https://drive.google.com/drive/folders/16Xk1eFSWjQTtuQivTogMmvL3P6F_084u?usp=sharing

**Comment by rongtongxueya** [comment]
I have just started exploring this area and would like to ask if there is any publicly available code for extracting embeddings from attribute text and features from images to save as .mat files? After using word2vector and BERT for extraction, I found that the embeddings for the same categories in the publicly available .mat files are very different from mine. I might have done something wrong, so I would like to learn and inquire if there is any reference code available for creating .mat files.
